- yaml.go
- yaml_test.go
Without this option the JSON decoder would tolerate
unknown fields.
looks like it was suggested earlier:
https://github.com/ghodss/yaml/pull/38#issuecomment-420416234
fixes #4 
/assign @dims 
/kind bug
cc @liztio
> UnmarshalStrict: use DisallowUnknownFields

- .travis.yml
drop support for go1.11
k/k 's minimal version is at 1.12 and this repository now requires modules.
this is a setup for this PR:
https://github.com/kubernetes-sigs/yaml/pull/19
/kind cleanup
/assign @dims
> CI: only test using 1.12.x

- README.md
instead of ghodss/yaml
Signed-off-by: Andrew Lavery <laverya@umich.edu>
> refer to kubernetes-sigs/yaml and sigs.k8s.io/yaml in readme

- yaml.go
- yaml_test.go
`JSONObjectToYAMLObject` is used to convert to a YAML MapSlice representation without going through a byte slice representation, which is too heavy on allocations for some applications.
> Add JSONObjectToYAMLObject

- .travis.yml
- go.mod
- go.sum
Fixes https://github.com/kubernetes-sigs/yaml/issues/24
`github.com/davecgh/go-spew` is required by `yaml_test.go` which was added in https://github.com/kubernetes-sigs/yaml/pull/14.
This was not caught in tests because we just run a `go test`, which updates `go.mod` but we don't check if there were any new changes. This PR fixes it.
/cc @sttts @neolit123 @dims
> Fix go.mod

- README.md
The blogpost's domain appears to have expired, so switch it to an archive.org link.
/sig docs
> Switch dead link to archive.org

- go.mod
- go.sum
- vendor/gopkg.in/yaml.v2/scannerc.go
- vendor/gopkg.in/yaml.v2/yamlh.go
- vendor/modules.txt
https://github.com/kubernetes/kubernetes/pull/87637#issuecomment-580910083
> upgrade gopkg.in/yaml.v2 to v2.2.8

- README.md
Fixes: https://github.com/kubernetes-sigs/yaml/issues/35
The original marshal result implies that the library will keep the sequence of json items while it actually doesn't. This PR is to avoid future confusion.
> Fix json to yaml marshal results

- go.sum
The current `go.sum` file is still importing different versions of `gopkg.in/yaml.v2`. As the version `v2.2.2` is affected by this advisory, dependency scanners will report the project as vulnerable (these tools can't figure out if the declared dependency is used or not based on this file).
> Tidy go modules

- yaml_test.go
In TestJSONObjectToYAMLObject the "uint64 big" case accepts a float64
of size 2^63. The value is passed to jsonToYAMLValue() and the
float64 branch of the switch is entered. For values that do not
fit int64 the first cast to int64() is undefined behavior
in most languages and apparently in Golang:
http://c0x.coding-guidelines.com/6.3.1.4.pdf
(link for the C standard)
This means the value of int64(float64(2^63)) can end up as either
-9223372036854775808 or 9223372036854775807.
From experimentation, it appears compiler optimization
determines the result.
The value is then casted back to float64 and matched against
the original float64, which may or may not pass. Depending of FPU
rounding mode for IEEE754-Doubles any input above 9223372036854775296
may get casted to 9223372036854775808.0. …
> yaml_test: adapt around undefined behavior in float64->int64 casting

- .github/workflows/go.yml
This PR attempts to resolve https://github.com/kubernetes-sigs/yaml/issues/48
> added github-actions CI

- .github/workflows/go.yml
This PR is in response to https://github.com/kubernetes-sigs/yaml/pull/50#discussion_r564588053
> removed go v1.12.x and added go v1.15.x in github-actions ci

- .travis.yml
Ref: https://github.com/kubernetes-sigs/yaml/issues/34#issuecomment-726326971
Skipping Go 1.14 because it was never used in any k8s release.
The `-race` flag is not supported on linux/arm.
Tests should fail until https://github.com/kubernetes-sigs/yaml/pull/42 is merged.
> Add CI tests for ARM64

- .gitignore
- go.mod
- go.sum
- vendor/gopkg.in/yaml.v2/.travis.yml
- vendor/gopkg.in/yaml.v2/apic.go
- vendor/gopkg.in/yaml.v2/go.mod
- vendor/gopkg.in/yaml.v2/yaml.go
- vendor/modules.txt
- yaml_test.go
Fixes https://github.com/kubernetes-sigs/yaml/issues/54 which is required to fix other issues like:
- https://github.com/kubernetes-sigs/controller-tools/issues/514
- https://github.com/go-yaml/yaml/issues/387
- https://github.com/kubernetes-sigs/kustomize/issues/947
- https://github.com/shipwright-io/build/issues/832
I have added a test case and tested it with version 2.2.8 of gopkg.in which breaks with:
```
--- FAIL: TestJSONToYAML (0.00s)
yaml_test.go:382: converting {"t":"a"}
yaml_test.go:382: converting {"t":null}
yaml_test.go:382: converting {"t":"this is very long line with spaces and it must be longer than 80 so we will repeat that it must be longer that 80"}
yaml_test.go:390: Failed to convert JSON to YAML, input: `{"t":"this is very long line with spaces and it must be longer …
```
> Bump gopkg.in/yaml.v2 to v2.4.0: fixes inconsistent long lines wrapping

- yaml_test.go
Somehow a variable with snake_case got in and it breaks linting.
> Fix lint error

- bench_test.go
This PR adds benchmarks in the yaml package to measure the performance of all public functions, so that any potential future improvements can be tested and compared.
Here is an example output of the benchmarks running on my machine:
```
$ go test . -bench=.
goos: linux
goarch: amd64
pkg: sigs.k8s.io/yaml
cpu: Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
BenchmarkMarshal-12                            4         250399990 ns/op          12.61 MB/s    378546400 B/op   2116671 allocs/op
BenchmarkUnmarshal-12                         13         102121267 ns/op          30.91 MB/s    123434972 B/op   1995357 allocs/op
BenchmarkUnmarshalStrict-12                   13         110663280 ns/op          28.53 MB/s    124146926 B/op   1995366 allocs/op
BenchmarkJSONToYAML-12                         5 …
```
> Add benchmarks

- go.mod
- go.sum
- yaml_test.go
Produces more compact test failures messages.
> Replace go-spew with go-cmp

- err_test.go
- yaml.go
Reverts some error message issues introduced since v1.3.0
The added unit test passes on the current released tag (v1.3.0) and the error message changes make it pass on master as well.
xref https://github.com/kubernetes-sigs/yaml/pull/76#issuecomment-1773339695
testing in k/k in https://github.com/kubernetes/kubernetes/pull/121407 - passed ✅ 
testing in kustomize in https://github.com/kubernetes-sigs/kustomize/pull/5406 - passed ✅
> Revert error message changes

- .github/workflows/go.yml
Something ends up requiring the slices package, which was added in Go 1.21.
See https://github.com/kubernetes-sigs/yaml/actions/runs/11232030744/job/31222775425?pr=118 for example:
```
Run GO111MODULE=off go get golang.org/x/lint/golint
GO111MODULE=off go get golang.org/x/lint/golint
shell: /usr/bin/bash -e {0}
env:
GOROOT: /opt/hostedtoolcache/go/1.16.15/x64
package slices: unrecognized import path "slices": import path does not begin with hostname
Error: Process completed with exit code 1.
```
> Test with Go 1.21 and later

- goyaml.v2/patch_test.go
- goyaml.v3/decode.go
- goyaml.v3/patch_test.go
> Handle unhashable keys during merge

- yaml.go
Currently `%v` is used inside an `Errorf` call, this means the original errors is lost and cannot be unwrapped to. 
By changing it to `%w` the error is preserved and can be retrieved with `errors.As`.
> fix: wrap errors returned by JSON unmarshal

- .github/workflows/go.yml
Things depending on this library are built with 1.24, so make sure it's also tested with it.
> Test against go 1.24.x

- go.mod
- go.sum
- kyaml/kyaml.go
- kyaml/kyaml_omitzero_test.go
- kyaml/kyaml_test.go
- yamlfmt/yamlfmt.go
KEP https://github.com/kubernetes/enhancements/issues/5295
KYAML is a strict subset of YAML, which is sort of halfway between YAML and JSON.  It has the following properties:
* Does not depend on whitespace (easier to text-patch and template).
* Always quotes value strings (no ambiguity aroud things like "no").
* Allows quoted keys, but does not require them, and only quotes them if they are not obviously safe (e.g. "no" would always be quoted).
* Always uses {} for structs and maps (no more obscure errors about mapping values).
* Always uses [] for lists (no more trying to figure out if a dash changes the meaning).
* When printing, it includes a header which makes it clear this is YAML and not ill-formed JSON.
* Allows trailing commas
* Allows comments,
* Tries to economize on vertical …
> Add "kyaml" support and yamlfmt
